busyconf:
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%=ENV['BUSYCONF_ROLLBAR_TOKEN']%>&environment=production
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['BUSYCONF_SLACK_TOKEN']%>

busyconf-staging:
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%=ENV['BUSYCONF_ROLLBAR_TOKEN']%>&environment=staging
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['BUSYCONF_SLACK_TOKEN']%>

busyconf-camo:
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['BUSYCONF_SLACK_TOKEN']%>

# so meta
busyconf-deploy-hooks:
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['BUSYCONF_SLACK_TOKEN']%>

chargestack:
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%=ENV['CHARGESTACK_ROLLBAR_TOKEN']%>&environment=production
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['CHARGESTACK_SLACK_TOKEN']%>

chargestack-staging:
  rollbar: https://api.rollbar.com/api/1/deploy/?access_token=<%=ENV['CHARGESTACK_ROLLBAR_TOKEN']%>&environment=staging
  slack: https://busyconf.slack.com/services/hooks/heroku?token=<%=ENV['CHARGESTACK_SLACK_TOKEN']%>
